---
- name: Install WordPress, MySQL, Nginx, and PHP-FPM
  hosts: wordpress
  become: true
  #  remote_user: root
  # remote_user: user
  # become_method: sudo

  roles:
    #  - common
    - mysql
    - nginx
    - php-fpm
    - wordpress
